stages:
  - npm
  - test

default:
  image: node:16

  before_script:
    - node --version
    - npm --version

npm:
  stage: npm
  script:
    - npm install
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

test:
  stage: test
  dependencies:
    - npm
  script:
    - npm test
